/* ══════════════════════════════════════════════════════════════════
   V9.0.13 · 의미 돌아보기 — 하루 한 장 + 2단계 기록 다시보기
   - 당사자 모드 전용, 날짜별 upsert, localStorage(ohg.v1) 안의 S.wbDays에만 저장
   - 오늘의 충동기록(S.urges)은 참고용으로만 읽고 의미기록에 복사 저장하지 않음
   - 기존 오늘 기록이 있으면 수정/처음부터 다시 작성 중 하나를 선택
   - 2단계 기록 다시보기는 선택형 칩만 단순 집계하며 자유입력은 분석하지 않음
   - 공허감 0~4는 자기평정이며 컷오프·위험색·판정을 붙이지 않음
   - 직접 입력 글은 분류·통계화하지 않음
   - 영역별 문장은 단일 회복영역에서만 추가하고, 복수영역은 공통문장만 제시
   ══════════════════════════════════════════════════════════════════ */
const MND=(window.MEANING_DATA&&typeof window.MEANING_DATA==='object')?window.MEANING_DATA:{};
const MN_HARD=Array.isArray(MND.hard)?MND.hard:[], MN_STRENGTH=Array.isArray(MND.strength)?MND.strength:[], MN_ACTION=Array.isArray(MND.action)?MND.action:[], MN_LINES=Array.isArray(MND.lines)?MND.lines:[];
function wbStore(){if(!S.wbDays||typeof S.wbDays!=='object'||Array.isArray(S.wbDays))S.wbDays={};return S.wbDays;}
function wbToday(){return ymd(new Date());}
function wbGet(d){const r=wbStore()[d];return(r&&typeof r==='object'&&!Array.isArray(r))?r:null;}
function mnItem(list,k){return list.find(x=>x.k===k)||null;}
function wbDateLabel(d){const t=ymdDate(d);if(!t)return String(d||'');return t.getFullYear()+'년 '+(t.getMonth()+1)+'월 '+t.getDate()+'일 '+'일월화수목금토'.charAt(t.getDay())+'요일';}
function wbAllowedLines(){const areas=(S.types||[]).filter(k=>['alcohol','gambling','drug','etc'].includes(k));const single=areas.length===1?areas[0]:'';return MN_LINES.filter(x=>{const scopes=Array.isArray(x.scope)?x.scope:[];if(scopes.includes('all'))return true;return !!single&&scopes.includes(single);});}
function wbLineCandidates(d,offset){const pool=wbAllowedLines();if(!pool.length)return[];const t=ymdDate(d),base=t?Math.floor(Date.UTC(t.getFullYear(),t.getMonth(),t.getDate())/86400000):0,start=((base+Number(offset||0))%pool.length+pool.length)%pool.length,out=[];for(let i=0;i<pool.length&&out.length<3;i++){const x=pool[(start+i)%pool.length];if(x&&!out.some(y=>y.id===x.id))out.push(x);}return out;}
function wbLineById(id){return MN_LINES.find(x=>x.id===id)||null;}
function wbTodayUrges(d){return (Array.isArray(S.urges)?S.urges:[]).filter(x=>x&&x.t&&ymd(Number(x.t))===d).sort((a,b)=>Number(b.t||0)-Number(a.t||0));}
function meaningUrgeLine(r){const tm=new Date(Number(r.t||Date.now())).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'}),typ=typeof typeOf==='function'?typeOf(r.type||'etc'):null,b=Number(r.b==null?0:r.b),a=r.a==null?null:Number(r.a),detail=typeof urgeDiarySummaryText==='function'?urgeDiarySummaryText(r):'';return '<div class="sp" style="align-items:flex-start;padding:7px 0"><span class="tiny" style="min-width:54px">'+esc(tm)+'</span><span style="flex:1"><b style="font-size:13px">'+esc((typ&&typ.n)||'회복')+' · 강도 '+b+(a==null?'':' → '+a)+'</b>'+(detail?'<span class="tiny" style="display:block;margin-top:2px">'+esc(detail)+'</span>':'')+'</span></div>';}
function drawMeaningUrges(d){const today=$('#mn-view-today');if(!today)return;let box=$('#mn-today-urges');if(!box){const note=today.querySelector('.note');if(!note)return;box=document.createElement('div');box.id='mn-today-urges';box.className='card';note.insertAdjacentElement('afterend',box);}const rows=wbTodayUrges(d);if(!rows.length){box.style.display='none';box.innerHTML='';return;}box.style.display='block';const show=rows.slice(0,3);box.innerHTML='<div class="sp" style="margin-bottom:5px"><h3 style="margin:0">오늘 기록된 충동 '+rows.length+'건</h3><span class="tiny">참고용</span></div><p class="tiny" style="margin:0 0 5px">이미 남긴 충동기록을 다시 입력하지 않고 오늘을 돌아볼 때 참고합니다. 의미기록에 복사 저장하지 않습니다.</p>'+show.map(meaningUrgeLine).join('')+(rows.length>3?'<p class="tiny" style="margin:5px 0 0">외 '+(rows.length-3)+'건이 더 있습니다.</p>':'')+'<button class="btn ghost sm" id="mn-open-urge-diary" type="button" style="margin-top:8px">충동일기에서 자세히 보기</button>';const b=$('#mn-open-urge-diary');if(b)b.onclick=()=>go('urge-diary');}
function meaningTopKeys(counts,limit){return Object.keys(counts).sort((a,b)=>counts[b]-counts[a]||String(a).localeCompare(String(b),'ko')).slice(0,limit);}
function drawMeaningHistorySummary(){const host=$('#mn-view-history');if(!host)return;let box=$('#mn-history-summary');if(!box){box=document.createElement('div');box.id='mn-history-summary';host.insertBefore(box,host.firstChild);}const rows=Object.keys(wbStore()).map(k=>wbGet(k)).filter(Boolean),strengthCount={},valueCount={};rows.forEach(r=>{(Array.isArray(r.strength)?r.strength:[]).forEach(k=>{if(mnItem(MN_STRENGTH,k))strengthCount[k]=(strengthCount[k]||0)+1;});(Array.isArray(r.action)?r.action:(Array.isArray(r.did)?r.did:[])).forEach(k=>{const a=mnItem(MN_ACTION,k);if(a&&a.value)valueCount[a.value]=(valueCount[a.value]||0)+1;});});const strengths=meaningTopKeys(strengthCount,4),values=meaningTopKeys(valueCount,3),chip=x=>'<span class="badge" style="margin:3px 5px 3px 0">'+esc(x)+'</span>';let html='<div class="card"><h3 style="margin-bottom:6px">내 기록에서 보이는 흐름</h3><p class="tiny" style="margin:0 0 10px">선택한 항목만 단순히 모아 보여줍니다. 직접 적은 글은 분류하거나 점수화하지 않습니다.</p>';if(!strengths.length&&!values.length)html+='<div class="empty" style="margin:6px 0">기록이 쌓이면 자주 보인 힘과 지킨 가치를 여기에서 확인할 수 있습니다.</div>';else{if(strengths.length)html+='<div style="margin-bottom:9px"><b style="font-size:13px">자주 보인 힘</b><div style="margin-top:5px">'+strengths.map(k=>chip((mnItem(MN_STRENGTH,k)||{}).l||k)).join('')+'</div></div>';if(values.length)html+='<div><b style="font-size:13px">자주 지킨 가치</b><div style="margin-top:5px">'+values.map(k=>chip((MND.values&&MND.values[k])||k)).join('')+'</div></div>';}html+='</div>';box.innerHTML=html;}

let mnDraft={d:'',hard:[],hardNote:'',strength:[],strengthNote:'',action:[],actionNote:'',empty:null,request:'',line:''},mnListAll=false,mnLineOffset=0,mnView='today',mnReplaceExisting=false;
function setMeaningView(v){mnView=v==='history'?'history':'today';const today=$('#mn-view-today'),history=$('#mn-view-history');if(today)today.classList.toggle('hide',mnView!=='today');if(history)history.classList.toggle('hide',mnView!=='history');$$('[data-mn-view]').forEach(b=>b.classList.toggle('on',b.dataset.mnView===mnView));if(mnView==='history'){drawMeaningHistorySummary();drawMeaningList();}const view=$('#view');if(view)view.scrollTop=0;}
function meaningDraftFrom(d,r){return {d,hard:(r&&Array.isArray(r.hard))?r.hard.slice():[],hardNote:(r&&r.hardNote)?String(r.hardNote):((r&&r.note)?String(r.note):''),strength:(r&&Array.isArray(r.strength))?r.strength.slice():[],strengthNote:(r&&r.strengthNote)?String(r.strengthNote):'',action:(r&&Array.isArray(r.action))?r.action.slice():((r&&Array.isArray(r.did))?r.did.slice():[]),actionNote:(r&&r.actionNote)?String(r.actionNote):'',empty:(r&&typeof r.empty==='number'&&r.empty>=0&&r.empty<=4)?r.empty:null,request:(r&&r.request)?String(r.request):'',line:(r&&r.line)?String(r.line):''};}
function renderMeaningDraft(d,r,restart){mnDraft=meaningDraftFrom(d,r);const allowedIds=new Set(wbAllowedLines().map(x=>x.id));if(mnDraft.line&&!allowedIds.has(mnDraft.line))mnDraft.line='';mnLineOffset=0;$('#mn-date').textContent=wbDateLabel(d)+(restart?' · 처음부터 다시 작성 중 · 기존 기록은 저장 전까지 유지됩니다.':(r?' · 오늘 기록이 있습니다':''));$('#mn-hard-note').value=mnDraft.hardNote;$('#mn-strength-note').value=mnDraft.strengthNote;$('#mn-action-note').value=mnDraft.actionNote;$('#mn-request').value=mnDraft.request;$('#mn-clear').style.display=r&&!restart?'':'none';drawMeaningChips();drawMeaningEmpty();drawMeaningLines();drawMeaningUrges(d);}
function showMeaningExistingChoice(d,r){modal('<h2>오늘 작성한 기록이 있습니다</h2><p class="muted" style="margin:6px 0 14px">기존 기록을 이어서 수정하거나, 빈 화면에서 처음부터 다시 작성할 수 있습니다.<br><b>처음부터 다시 작성해도 새 내용을 저장하기 전까지 기존 기록은 지워지지 않습니다.</b></p><button class="btn" id="mn-edit-existing">기존 기록 수정하기</button><button class="btn ghost" id="mn-restart-existing" style="margin-top:8px">처음부터 다시 작성</button>');$('#mn-edit-existing').onclick=()=>{mnReplaceExisting=false;closeModal();renderMeaningDraft(d,r,false);};$('#mn-restart-existing').onclick=()=>{mnReplaceExisting=true;closeModal();renderMeaningDraft(d,null,true);setMeaningView('today');};}
function drawMeaning(opts){if(famMode()){go('tools',{replace:true});return;}const d=wbToday(),r=wbGet(d),skipPrompt=!!(opts&&opts.skipExistingPrompt);mnReplaceExisting=false;renderMeaningDraft(d,r,false);drawMeaningHistorySummary();drawMeaningList();setMeaningView('today');if(r&&!skipPrompt)setTimeout(()=>showMeaningExistingChoice(d,r),0);}
function drawMeaningChips(){const fill=(box,list,picked)=>{if(!box)return;box.innerHTML='';list.forEach(x=>{const b=el('button','opt'+(picked.includes(x.k)?' on':''),'<span>'+esc(x.l)+'</span>');b.onclick=()=>{const i=picked.indexOf(x.k);if(i<0)picked.push(x.k);else picked.splice(i,1);drawMeaningChips();};box.appendChild(b);});};fill($('#mn-hard'),MN_HARD,mnDraft.hard);fill($('#mn-strength'),MN_STRENGTH,mnDraft.strength);fill($('#mn-action'),MN_ACTION,mnDraft.action);}
function drawMeaningEmpty(){const box=$('#mn-empty');if(!box)return;box.innerHTML='';[0,1,2,3,4].forEach(v=>{const b=el('button',mnDraft.empty===v?'on':'',String(v));b.onclick=()=>{mnDraft.empty=v;drawMeaningEmpty();};box.appendChild(b);});$('#mn-empty-skip').style.display=typeof mnDraft.empty==='number'?'':'none';}
function drawMeaningLines(){const box=$('#mn-lines'),more=$('#mn-lines-more');if(!box||!more)return;const pool=wbAllowedLines(),cand=wbLineCandidates(mnDraft.d||wbToday(),mnLineOffset),selected=pool.find(x=>x.id===mnDraft.line);if(selected&&!cand.some(x=>x.id===selected.id)){cand.unshift(selected);if(cand.length>3)cand.pop();}box.innerHTML='';cand.forEach(x=>{const b=el('button','mn-line-opt'+(mnDraft.line===x.id?' on':''),esc(x.text));b.onclick=()=>{mnDraft.line=mnDraft.line===x.id?'':x.id;drawMeaningLines();};box.appendChild(b);});if(!cand.length)box.innerHTML='<div class="empty">지금 보여드릴 공통 문장이 없습니다.</div>';more.style.display=pool.length>3?'':'none';}
function drawMeaningList(){const st=wbStore(),keys=Object.keys(st).filter(k=>wbGet(k)).sort().reverse(),box=$('#mn-list'),more=$('#mn-more');if(!keys.length){box.innerHTML='<div class="empty" style="margin:8px 0">아직 남긴 기록이 없습니다.</div>';more.style.display='none';return;}const show=mnListAll?keys:keys.slice(0,14);box.innerHTML=show.map(k=>{const r=st[k],parts=[],h=(r.hard||[]).map(x=>(mnItem(MN_HARD,x)||{}).l).filter(Boolean),stg=(r.strength||[]).map(x=>(mnItem(MN_STRENGTH,x)||{}).l).filter(Boolean),act=(r.action||r.did||[]).map(x=>(mnItem(MN_ACTION,x)||{}).l).filter(Boolean);if(typeof r.empty==='number')parts.push('<em>공허감</em> '+Number(r.empty));if(h.length)parts.push('<em>아팠던 것</em> '+esc(h.join(' · ')));if(r.hardNote||r.note)parts.push('<em>직접 기록</em> '+esc(String(r.hardNote||r.note)));if(stg.length)parts.push('<em>남아 있던 힘</em> '+esc(stg.join(' · ')));if(r.strengthNote)parts.push('<em>힘 · 직접</em> '+esc(String(r.strengthNote)));if(act.length)parts.push('<em>선택·지킨 것</em> '+esc(act.join(' · ')));if(r.actionNote)parts.push('<em>선택 · 직접</em> '+esc(String(r.actionNote)));if(r.request)parts.push('<em>삶의 요청</em> '+esc(String(r.request)));const line=wbLineById(r.line);if(line)parts.push('<em>오늘의 문장</em> '+esc(line.text));return '<div class="mn-day"><span class="d">'+esc(wbDateLabel(k))+'</span><span class="c">'+(parts.length?parts.join('<br>'):'<em>비어 있음</em>')+'</span></div>';}).join('');more.style.display=keys.length>14?'':'none';more.textContent=mnListAll?'최근 기록만 보기':'지난 기록 모두 보기';}
function meaningCollected(){const hardNote=$('#mn-hard-note').value.trim(),strengthNote=$('#mn-strength-note').value.trim(),actionNote=$('#mn-action-note').value.trim(),request=$('#mn-request').value.trim(),any=mnDraft.hard.length||hardNote||mnDraft.strength.length||strengthNote||mnDraft.action.length||actionNote||typeof mnDraft.empty==='number'||request||mnDraft.line,rec={hard:mnDraft.hard.slice(),strength:mnDraft.strength.slice(),action:mnDraft.action.slice(),ts:Date.now()};if(hardNote)rec.hardNote=hardNote;if(strengthNote)rec.strengthNote=strengthNote;if(actionNote)rec.actionNote=actionNote;if(typeof mnDraft.empty==='number')rec.empty=mnDraft.empty;if(request)rec.request=request;if(mnDraft.line)rec.line=mnDraft.line;return {any:!!any,rec};}
function saveMeaningRecord(replaceConfirmed){if(famMode()){toast('의미 돌아보기는 당사자 모드에서 사용합니다.');go('tools',{replace:true});return;}const st=wbStore(),d=mnDraft.d||wbToday(),existing=!!st[d],x=meaningCollected();if(!x.any){if(mnReplaceExisting&&existing){toast('새로 작성할 내용이 없습니다. 기존 기록은 그대로 유지됩니다.');return;}if(existing){delete st[d];save();toast('오늘 기록을 지웠습니다.');drawMeaning({skipExistingPrompt:true});}else toast('아무것도 남기지 않으면 기록을 만들지 않습니다.');return;}if(mnReplaceExisting&&existing&&!replaceConfirmed){modal('<h2>기존 오늘 기록을 바꿀까요?</h2><p class="muted" style="margin:6px 0 14px">새로 작성한 내용을 저장하면 기존 오늘 기록은 이 내용으로 교체됩니다.</p><button class="btn" id="mn-replace-yes">새 내용으로 바꾸기</button><button class="btn ghost" onclick="closeModal()" style="margin-top:8px">계속 작성하기</button>');$('#mn-replace-yes').onclick=()=>{closeModal();saveMeaningRecord(true);};return;}st[d]=x.rec;save();mnReplaceExisting=false;toast(existing?'오늘 기록을 수정했습니다.':'오늘 기록을 저장했습니다.');drawMeaning({skipExistingPrompt:true});}

$('#mn-empty-skip').onclick=()=>{mnDraft.empty=null;drawMeaningEmpty();};
$('#mn-lines-more').onclick=()=>{mnLineOffset+=3;drawMeaningLines();};
$('#mn-more').onclick=()=>{mnListAll=!mnListAll;drawMeaningList();};
$$('[data-mn-view]').forEach(b=>b.onclick=()=>setMeaningView(b.dataset.mnView));
$('#mn-save').onclick=()=>saveMeaningRecord(false);
$('#mn-clear').onclick=()=>{const d=mnDraft.d||wbToday();modal('<h2>오늘 기록을 지울까요?</h2><p class="muted" style="margin:6px 0 14px">'+esc(wbDateLabel(d))+'에 남긴 것이 지워집니다. 다른 날의 기록은 그대로입니다.</p><button class="btn danger" id="mn-clear-yes">지우기</button><button class="btn ghost" onclick="closeModal()" style="margin-top:8px">그만두기</button>');$('#mn-clear-yes').onclick=()=>{const st=wbStore();if(st[d]){delete st[d];save();}closeModal();mnReplaceExisting=false;toast('오늘 기록을 지웠습니다.');drawMeaning({skipExistingPrompt:true});};};
$('#tool-meaning').onclick=()=>{if(famMode()){toast('의미 돌아보기는 당사자 모드에서 사용합니다.');return;}go('meaning');};
$('#ni-meaning').onclick=()=>{if(famMode())return;niAfter='meaning';$('#ni-save').click();};
