from pathlib import Path
import re

idx=Path('index.html'); sw=Path('sw.js')
s=idx.read_text(encoding='utf-8'); w=sw.read_text(encoding='utf-8')

assert "const BUILD = 'V8.2.17';" in s
s=s.replace("const BUILD = 'V8.2.17';","const BUILD = 'V8.2.18';",1)

# 도움이 되지 않는 사고방식: 빠른 보기 기본 접힘 아코디언
pat=r"function smartThinkingReference\(\)\{\n return .*?\n\}"
repl=r'''function smartThinkingReferenceToggle(btn){
 const acc=btn&&btn.closest?btn.closest('.acc'):null;if(!acc)return;
 const open=!acc.classList.contains('on');acc.classList.toggle('on',open);btn.setAttribute('aria-expanded',open?'true':'false');
}
function smartThinkingReference(){
 const rows=SMART_THINKING_STYLES.map((x,i)=>'<div style="padding:10px 0;'+(i?'border-top:1px solid var(--line)':'')+'"><b>'+(i+1)+'. '+esc(x.name)+'</b><div class="tiny" style="margin-top:2px">'+esc(x.en)+'</div><div class="muted" style="margin-top:4px">'+esc(x.desc)+'</div></div>').join('');
 return '<div class="acc" id="smart-thinking-reference"><button class="acc-h" type="button" aria-expanded="false" onclick="smartThinkingReferenceToggle(this)"><div class="acc-n"><b>8가지 사고방식 빠르게 보기</b><span>필요할 때 펼쳐서 확인합니다.</span></div><svg class="acc-v" viewBox="0 0 24 24"><path d="m6 9 6 6 6-6"/></svg></button><div class="acc-b">'+rows+'</div></div>';
}'''
s,n=re.subn(pat,repl,s,count=1,flags=re.S)
assert n==1

# 문제 해결 편집기: 단계/전략을 한 번에 하나만 여는 아코디언으로 변경
pat=r"function smartProblemStrategyCard\(x,i\)\{.*?\n\}\nfunction smartProblemSection"
repl=r'''function smartProblemStrategyCard(x,i,open){
 x=x||{};const summary=String(x.text||'').trim()||'내용을 입력하세요.';
 return '<div class="acc'+(open?' on':'')+'" data-ps-row="'+i+'"><button class="acc-h" type="button" data-ps-strategy-toggle="'+i+'" aria-expanded="'+(open?'true':'false')+'"><div class="acc-n"><b>전략 '+(i+1)+'</b><span data-ps-summary="'+i+'">'+esc(summary)+'</span></div><svg class="acc-v" viewBox="0 0 24 24"><path d="m6 9 6 6 6-6"/></svg></button><div class="acc-b"><div style="text-align:right;margin-bottom:8px"><button type="button" class="tiny" style="color:var(--bad);font-weight:600" data-ps-remove="'+i+'">이 전략 삭제</button></div><div class="field"><label>가능한 전략</label><textarea data-ps-text="'+i+'" maxlength="500" placeholder="판단하지 말고 가능한 아이디어를 적어보세요.">'+esc(x.text||'')+'</textarea></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px"><div class="field"><label>실행 가능성 0~10</label><input data-ps-feasible="'+i+'" type="number" min="0" max="10" value="'+smartProblemClamp(x.feasible)+'"></div><div class="field"><label>시도할 준비 0~10</label><input data-ps-ready="'+i+'" type="number" min="0" max="10" value="'+smartProblemClamp(x.ready)+'"></div></div><div class="field"><label>좋은 점</label><textarea data-ps-good="'+i+'" maxlength="500" placeholder="이 전략의 좋은 점은 무엇인가요?">'+esc(x.good||'')+'</textarea></div><div class="field"><label>가능한 위험</label><textarea data-ps-risk="'+i+'" maxlength="500" placeholder="어떤 위험이나 어려움이 있을 수 있나요?">'+esc(x.risk||'')+'</textarea></div><div class="field"><label>종합 점수 0~10</label><input data-ps-score="'+i+'" type="number" min="0" max="10" value="'+smartProblemClamp(x.score)+'"></div></div></div>';
}
function openSmartProblemEditor(record){
 const r=record||{};
 let strategies=(Array.isArray(r.strategies)&&r.strategies.length?r.strategies:[{id:'ps-'+Date.now(),text:'',feasible:0,ready:0,good:'',risk:'',score:0}]).map(x=>Object.assign({},x));
 let selectedId=r.selectedId||'';
 const setAcc=(acc,open)=>{if(!acc)return;acc.classList.toggle('on',open);const b=Array.from(acc.children).find(x=>x.classList&&x.classList.contains('acc-h'));if(b)b.setAttribute('aria-expanded',open?'true':'false');};
 const collectRows=()=>{strategies=strategies.map((x,i)=>({id:x.id||('ps-'+Date.now()+'-'+i),text:($('[data-ps-text="'+i+'"]')||{}).value?.trim()||'',feasible:smartProblemClamp(($('[data-ps-feasible="'+i+'"]')||{}).value),ready:smartProblemClamp(($('[data-ps-ready="'+i+'"]')||{}).value),good:($('[data-ps-good="'+i+'"]')||{}).value?.trim()||'',risk:($('[data-ps-risk="'+i+'"]')||{}).value?.trim()||'',score:smartProblemClamp(($('[data-ps-score="'+i+'"]')||{}).value)}));return strategies;};
 const renderSelection=()=>{const box=$('#ps-selection');if(!box)return;const filled=strategies.filter(x=>String(x.text||'').trim());if(!filled.length){box.innerHTML='<div class="note">브레인스토밍에서 가능한 전략을 먼저 적어주세요.</div>';return;}box.innerHTML=filled.map((x,i)=>'<label style="display:flex;gap:10px;align-items:flex-start;padding:11px 0;'+(i?'border-top:1px solid var(--line)':'')+'"><input type="radio" name="ps-selected" data-ps-choice value="'+esc(x.id)+'" style="width:19px;height:19px;flex:0 0 auto;margin-top:2px" '+(x.id===selectedId?'checked':'')+'><span><b>'+esc(x.text)+'</b><span class="tiny" style="display:block;margin-top:3px">실행 가능성 '+smartProblemClamp(x.feasible)+'/10 · 준비 '+smartProblemClamp(x.ready)+'/10 · 종합 '+smartProblemClamp(x.score)+'/10</span></span></label>').join('');box.querySelectorAll('[data-ps-choice]').forEach(c=>c.onchange=()=>{if(c.checked)selectedId=c.value;});};
 const renderRows=(openIndex)=>{const box=$('#ps-strategies');if(!box)return;box.innerHTML=strategies.map((x,i)=>smartProblemStrategyCard(x,i,i===openIndex)).join('');box.querySelectorAll('[data-ps-strategy-toggle]').forEach(b=>b.onclick=()=>{const target=b.closest('[data-ps-row]'),was=target.classList.contains('on');box.querySelectorAll('[data-ps-row]').forEach(a=>setAcc(a,false));if(!was)setAcc(target,true);});box.querySelectorAll('[data-ps-text]').forEach(t=>t.oninput=()=>{const n=box.querySelector('[data-ps-summary="'+t.dataset.psText+'"]');if(n)n.textContent=t.value.trim()||'내용을 입력하세요.';});box.querySelectorAll('[data-ps-remove]').forEach(b=>b.onclick=()=>{if(strategies.length<=1){toast('전략을 하나 이상 남겨주세요.');return;}collectRows();const removed=strategies.splice(+b.dataset.psRemove,1)[0];if(removed&&removed.id===selectedId)selectedId='';renderRows(Math.min(+b.dataset.psRemove,strategies.length-1));renderSelection();});};
 const openStep=(name,scroll)=>{if(name==='select'){collectRows();renderSelection();}const editor=$('#ps-editor');if(!editor)return;editor.querySelectorAll('[data-ps-step]').forEach(a=>setAcc(a,false));const target=editor.querySelector('[data-ps-step="'+name+'"]');setAcc(target,true);if(scroll&&target)setTimeout(()=>target.scrollIntoView({behavior:'smooth',block:'start'}),30);};
 modal('<h2>'+(record?'문제 해결 수정':'문제 해결 · 5단계')+'</h2><p class="muted" style="margin:5px 0 14px">문제를 작게 나누고, 해결책을 판단하기 전에 충분히 떠올린 다음, 현실적으로 평가하고 하나를 골라 글로 계획합니다.</p><div id="ps-editor">'
 +'<div class="acc on" data-ps-step="definition"><button class="acc-h" type="button" data-ps-step-toggle="definition" aria-expanded="true"><div class="acc-n"><b>1 · 문제 정의</b><span>언제 · 누가 · 무슨 일 · 생각과 감정을 구체적으로 적습니다.</span></div><svg class="acc-v" viewBox="0 0 24 24"><path d="m6 9 6 6 6-6"/></svg></button><div class="acc-b">'+smartProblemField('문제는 일반적으로 언제 발생합니까? 언제 일어날 가능성이 있습니까?','ps-when',r.when,'언제, 어떤 때 반복되나요?','최대한 구체적으로 작성합니다.',700)+smartProblemField('누가 관련되어 있나요? 또 누가 참여할 가능성이 있나요?','ps-who',r.who,'관련된 사람을 적어보세요.','',500)+smartProblemField('보통 무슨 일이 일어나나요? 무슨 일이 일어날 것 같나요?','ps-what',r.what,'실제로 일어나는 일을 구체적으로 적어보세요.','',800)+smartProblemField('이 상황에 대한 나의 일반적인 생각과 감정은 무엇입니까?','ps-thoughts',r.thoughts,'그때 반복되는 생각과 감정을 적어보세요.','',900)+'<button class="btn sec" type="button" id="ps-next-brainstorm">다음 · 브레인스토밍</button></div></div>'
 +'<div class="acc" data-ps-step="brainstorm"><button class="acc-h" type="button" data-ps-step-toggle="brainstorm" aria-expanded="false"><div class="acc-n"><b>2 · 브레인스토밍</b><span>가능한 전략을 떠올리고 각 전략의 평가를 함께 작성합니다.</span></div><svg class="acc-v" viewBox="0 0 24 24"><path d="m6 9 6 6 6-6"/></svg></button><div class="acc-b"><div class="note" style="margin-bottom:10px">먼저 판단하지 말고 가능한 해결책을 최대한 많이 떠올립니다. “그건 안 될 거야”라고 미리 제외하지 않습니다.</div><div class="tiny" style="margin-bottom:10px">번역본의 3단계 ‘평가’는 각 전략을 펼쳐 실행 가능성·시도할 준비·좋은 점·위험·종합점수를 작성하는 방식으로 함께 진행합니다.</div><div id="ps-strategies"></div><button class="btn sec" type="button" id="ps-add">+ 가능한 전략 추가</button><div style="height:8px"></div><button class="btn ghost" type="button" id="ps-next-select">다음 · 전략 선택</button></div></div>'
 +'<div class="acc" data-ps-step="select"><button class="acc-h" type="button" data-ps-step-toggle="select" aria-expanded="false"><div class="acc-n"><b>3 · 전략 선택</b><span>평가를 비교하고 실제로 시도할 전략 하나를 고릅니다.</span></div><svg class="acc-v" viewBox="0 0 24 24"><path d="m6 9 6 6 6-6"/></svg></button><div class="acc-b"><div id="ps-selection"></div><button class="btn sec" type="button" id="ps-next-plan" style="margin-top:10px">다음 · 서면 계획</button></div></div>'
 +'<div class="acc" data-ps-step="plan"><button class="acc-h" type="button" data-ps-step-toggle="plan" aria-expanded="false"><div class="acc-n"><b>4 · 서면으로 계획 작성하기</b><span>선택한 전략을 언제 · 어디서 · 어떻게 실행할지 구체화합니다.</span></div><svg class="acc-v" viewBox="0 0 24 24"><path d="m6 9 6 6 6-6"/></svg></button><div class="acc-b">'+smartProblemField('선택한 해결책을 어떻게 실행할까요?','ps-plan',r.plan,'무엇을, 어떤 순서로 실행할지 적어보세요.','머릿속 계획보다 글로 적은 계획이 실행에 도움이 됩니다.',1000)+'<div style="display:grid;grid-template-columns:1fr 1fr;gap:8px"><div class="field"><label>시작 날짜</label><input id="ps-start" type="date" value="'+esc(r.start||'')+'"></div><div class="field"><label>장소</label><input id="ps-place" maxlength="120" value="'+esc(r.place||'')+'" placeholder="어디에서 시작할까요?"></div></div>'+smartProblemField('성공에 필요한 것·도움','ps-needs',r.needs,'필요한 준비, 사람, 자원 등을 적어보세요.','',700)+smartProblemField('실행 후 결과 점검','ps-review',r.review,'계획이 효과가 있었나요? 무엇을 수정하거나 다른 해결책을 시도해야 하나요?','실행 후 다시 열어 기록해도 됩니다.',800)+'</div></div></div><button class="btn" id="ps-save">'+(record?'수정 저장':'문제 해결 저장')+'</button><div style="height:8px"></div><button class="btn ghost" onclick="closeModal()">취소</button>');
 renderRows(0);renderSelection();
 const editor=$('#ps-editor');editor.querySelectorAll('[data-ps-step-toggle]').forEach(b=>b.onclick=()=>{const target=b.closest('[data-ps-step]'),was=target.classList.contains('on');if(was){setAcc(target,false);return;}openStep(b.dataset.psStepToggle,false);});
 $('#ps-next-brainstorm').onclick=()=>openStep('brainstorm',true);
 $('#ps-next-select').onclick=()=>openStep('select',true);
 $('#ps-next-plan').onclick=()=>openStep('plan',true);
 $('#ps-add').onclick=()=>{collectRows();strategies.push({id:'ps-'+Date.now()+'-'+Math.random().toString(36).slice(2,6),text:'',feasible:0,ready:0,good:'',risk:'',score:0});renderRows(strategies.length-1);setTimeout(()=>{const rows=$$('[data-ps-row]');if(rows.length)rows[rows.length-1].scrollIntoView({behavior:'smooth',block:'center'});},30);};
 $('#ps-save').onclick=()=>{const rows=collectRows().filter(x=>x.text);const what=$('#ps-what').value.trim();if(!what){toast('보통 무슨 일이 일어나는지 적어주세요.');openStep('definition',true);return;}if(!rows.length){toast('가능한 전략을 하나 이상 적어주세요.');openStep('brainstorm',true);return;}const selected=rows.find(x=>x.id===selectedId);if(!selected){toast('시도할 전략 하나를 선택해주세요.');openStep('select',true);return;}const plan=$('#ps-plan').value.trim();if(!plan){toast('선택한 해결책의 실행 계획을 적어주세요.');openStep('plan',true);return;}const rec={id:record?record.id:('problem-'+Date.now()+'-'+Math.random().toString(36).slice(2,7)),kind:'problem-solving',role:famMode()?'family':'self',ts:record?(record.ts||Date.now()):Date.now(),updatedAt:Date.now(),when:$('#ps-when').value.trim(),who:$('#ps-who').value.trim(),what,thoughts:$('#ps-thoughts').value.trim(),strategies:rows.map(x=>({id:x.id,text:x.text,feasible:x.feasible,ready:x.ready,good:x.good,risk:x.risk,score:x.score})),selectedId:selected.id,selectedText:selected.text,plan,start:$('#ps-start').value,place:$('#ps-place').value.trim(),needs:$('#ps-needs').value.trim(),review:$('#ps-review').value.trim()};if(!Array.isArray(S.smartWorks))S.smartWorks=[];if(record){const i=S.smartWorks.findIndex(x=>x&&x.id===record.id);if(i>=0)S.smartWorks[i]=rec;else S.smartWorks.push(rec);}else S.smartWorks.push(rec);save();closeModal();drawSmartProblemSolving();toast(record?'문제 해결 기록을 수정했습니다.':'문제 해결 기록을 저장했습니다.');};
}
function smartProblemSection'''
s,n=re.subn(pat,repl,s,count=1,flags=re.S)
assert n==1

assert "const APP_VERSION = 'V8.2.17';" in w
w=w.replace("const APP_VERSION = 'V8.2.17';","const APP_VERSION = 'V8.2.18';",1)
w=w.replace("const V = 'ohg-v8217-smart-problem-solving';","const V = 'ohg-v8218-smart-accordion';",1)

idx.write_text(s,encoding='utf-8'); sw.write_text(w,encoding='utf-8')
